name: go_together
description: A carpool app with Firebase Auth, ride booking, and SOS features.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core and Auth
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_database: ^10.5.7
  firebase_messaging: ^14.9.4
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.7.6

  # Google Maps and Geolocator
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_polyline_points: ^1.0.0
  intl: ^0.19.0
  http: ^0.13.6

  # Image and URL handling
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  flutter_svg: ^2.0.9

  # Charts and UI
  fl_chart: ^0.66.2
  lottie: ^2.7.0
  shimmer: ^3.0.0
  google_fonts: ^4.0.4
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0

  # Other common dependencies
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/animations/